"""Add RecurringExpense model

Revision ID: d4559fc3bf16
Revises: 
Create Date: 2024-12-24 01:18:40.023634

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd4559fc3bf16'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recurring_expense')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_expense',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('userId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('expense_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('amount', mysql.FLOAT(), nullable=False),
    sa.Column('frequency', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
